version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=name
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    command: npm start
    volumes:
      - ./html:/usr/src/app
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      - DB_NAME=name
      - DB_USER=user
      - DB_PASSWORD=pass
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./starter:/usr/src/app
    ports:
      - "8000:8000"